"""fix number_phone

Revision ID: 25fc2a8efaab
Revises: 549c0c93972d
Create Date: 2024-02-05 16:28:04.712960

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '25fc2a8efaab'
down_revision = '549c0c93972d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('requisites', schema=None) as batch_op:
        batch_op.add_column(sa.Column('number_phone', sa.BigInteger(), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('requisites', schema=None) as batch_op:
        batch_op.drop_column('number_phone')

    # ### end Alembic commands ###
