"""fix number_phone

Revision ID: 3b4f2d0be68e
Revises: 25fc2a8efaab
Create Date: 2024-02-05 16:32:10.661621

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3b4f2d0be68e'
down_revision = '25fc2a8efaab'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('requisites', schema=None) as batch_op:
        batch_op.alter_column('number_phone',
               existing_type=sa.BIGINT(),
               type_=sa.String(),
               existing_nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('requisites', schema=None) as batch_op:
        batch_op.alter_column('number_phone',
               existing_type=sa.String(),
               type_=sa.BIGINT(),
               existing_nullable=False)

    # ### end Alembic commands ###
